name: Build and upload binary

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get the release version from the tag
      shell: bash
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    # - name: Run tests
    #   run: cargo test --verbose
    - name: Build
      run: cargo build --release --verbose
    - name: Upload the binary
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/xssh
